//creación tabla de estado
CREATE TABLE FIDE_ESTADO_TB(
estado_id_estado_pk number generated by default on null as identity primary key,
descripcion varchar2(200));
/
CREATE TABLE FIDE_ROL_TB(
rol_id_rol_pk number generated by default on null as identity primary key,
nombre_rol varchar2(100));
/
CREATE TABLE FIDE_TIPOPLATILLO_TB(
tipoplatillo_id_tipoplatillo_pk number generated by default on null as identity primary key,
descripcion varchar2(200));
/
CREATE TABLE FIDE_TIPOKART_TB(
tipokart_id_tipokart_pk number generated by default on null as identity primary key,
descripcion varchar2(200));

